FROM python:3.11-slim

RUN pip install poetry==1.8.4

ENV POETRY_NO_INTERACTION=1 \
    POETRY_VIRTUALENVS_IN_PROJECT=1 \
    POETRY_VIRTUALENVS_CREATE=1 \
    POETRY_CACHE_DIR=/tmp/poetry_cache

WORKDIR /app

# Copy only the Poetry configuration first to leverage Docker layer caching
COPY pyproject.toml poetry.lock /app/
RUN touch README.md

# Install dependencies without dev packages
RUN poetry install --without dev --no-root && rm -rf $POETRY_CACHE_DIR

# Copy the rest of the application files into the container
COPY . /app

# Install the local project into the Poetry environment
RUN poetry install --without dev --no-interaction --no-ansi

ENTRYPOINT ["poetry", "run", "python", "/app/recorder.py"]
